web01:
  build: .
  expose:
    - 80
  links:
    - mysql01

web02:
  build: .
  expose:
    - 80
  links:
    - mysql02

haproxy:
  image: haproxy
  volumes:
    - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
  links:
    - web01
    - web02
  ports:
    - "8080:80"
    - "70:70"
  expose:
    - "8080"
    - "70"

mysql01:
  image: mysql
  volumes:
    - ./mysql01/conf.d:/etc/mysql/conf.d
    - ./mysql01/data:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: 123456
    MYSQL_USER: dev
    MYSQL_PASSWORD: 123456
    MYSQL_DATABASE: app
  expose:
    - 3306

mysql02:
  image: mysql
  volumes:
    - ./mysql02/conf.d:/etc/mysql/conf.d
    - ./mysql02/data:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: 123456
    MYSQL_USER: dev
    MYSQL_PASSWORD: 123456
    MYSQL_DATABASE: app
  expose:
    - 3306
  links:
    - mysql01
