version: '2'

services:
  web01:
    build: .
    environment:
      - MYSQLSERVERNAME=mysql01
      - DPAPI_PATH=/dpapi
    depends_on:
      - mysql01
    volumes:
      - ./published-app:/app:ro
  
  web02:
    build: .
    environment:
      - MYSQLSERVERNAME=mysql02
      - DPAPI_PATH=/dpapi
    depends_on:
      - mysql02
    volumes:
      - ./published-app:/app:ro
  
  haproxy:
    image: haproxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "8080:80" # We want port 8080 available to let us test
      - "70:70"   # We want to be able to see statistics of HAProxy
    depends_on:
      - web01
      - web02
  
  mysql01:
    image: mysql
    volumes:
      - ./mysql01/conf.d:/etc/mysql/conf.d:ro
      - ./mysql01/data:/var/lib/mysql:rw # MySQL data needs to be read-write
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: app
  
  mysql02:
    image: mysql
    volumes:
      - ./mysql02/conf.d:/etc/mysql/conf.d:ro
      - ./mysql02/data:/var/lib/mysql:rw # MySQL data needs to be read-write
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: app
