version: '2'

services:
  web01:
    build: .
    expose:
      - 80
    environment:
      - MYSQLSERVERNAME=mysql01
      - DPAPI_PATH=/dpapi
    depends_on:
      - mysql01
    volumes:
      - ./dpapi:/dpapi
      - ./published-app:/app
  
  web02:
    build: .
    expose:
      - 80
    environment:
      - MYSQLSERVERNAME=mysql02
      - DPAPI_PATH=/dpapi
    depends_on:
      - mysql02
    volumes:
      - ./dpapi:/dpapi
      - ./published-app:/app
  
  haproxy:
    image: haproxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "8080:80"
      - "70:70"
    expose:
      - "8080"
      - "70"
    depends_on:
      - web01
      - web02
  
  mysql01:
    image: mysql
    volumes:
      - ./mysql01/conf.d:/etc/mysql/conf.d
      - ./mysql01/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: app
    expose:
      - 3306
    ports:
      - 3316:3306
  
  mysql02:
    image: mysql
    volumes:
      - ./mysql02/conf.d:/etc/mysql/conf.d
      - ./mysql02/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: app
    expose:
      - 3306
    ports:
      - 3326:3306
